### ISSUE TITLE
Add React-Router

### ISSUE THREAD

**Issue by solbijae** [solbijae/mbtiTranslator#2]
### ✅ To-do
- [ ] Setup React-Router
- [ ] Add http://localhost:5173/mbti/*
- [ ] Add http://localhost:5173/mbti/{{Individual MBTI Pages}}
